repository:
  # A short description of the repository that will show up on GitHub
  description: Special settings repo

# The following attributes are applied to any repo within the org
# So if a repo is not listed above is created or edited
# The app will apply the following settings to it
labels:
  # Labels: define labels for Issues and Pull Requests
  include:
    - name: bug
      color: CC0000
      description: An issue with the system

    - name: feature
      # If including a `#`, make sure to wrap it with quotes!
      color: "#336699"
      description: New functionality.

    - name: new-label
      # include the old name to rename an existing label
      oldname: Help Wanted
      color: "#326699"
  exclude:
    # don't delete any labels created on GitHub that starts with "release"
    - name: ^release